@extends('layout.profile-layout')

@section('profile-content')
@include('partials.upper-part')
<br>
<br>
<br>
<br>
@include('partials.bottom-part')
@include('partials.bottom-part-photos')
<br>
<br>
<br>
<br>
<br>
<br>
<br>
@include('partials.bottom-part-grey')
@endsection